Blogger\BlogBundle\Entity\Post:
    properties:
        username:
            - NotBlank: ~
        useremail:
            - NotBlank: ~
            - Email: ~
        message:
            - NotBlank: ~
            - Length:
                min: 2
                max: 1000
